### PR TITLE
isru

### PR DESCRIPTION
**Pull request by yalov**
* LF, LH2, LCH4 fills the same-volume tank in the same time and use the same amount of ore.  
 * LFO, LH2O, LCH4O fills the same-volume tank in the same time and use the same amount of ore.  
 * Opt-in system for easy support in other mods or local (mining expansion included)
 * CryoConverters depends on LF and LFO converters, so user patches that changes LF or LFO also changes CryoConverters accordingly

### CODE REVIEW

**Comment by yalov** [comment]
in the result, all CryoConverters are nerfed, the largest nerf is for the LH2:

ISRU 250:
before: 1.0 Ore -> 141 LH2
after: 0.45 Ore -> 6.75 LH2

ISRU 125:
before: 2.0 Ore  -> 141 LH2
after:    2.25 Ore -> 3.375 LH2

**Comment by ChrisAdderley** [comment]
The 'fills the same tank volume' is odd. The baseline should follow these rules (probably)
- Uses the same input ore rate as the stock converters
- Converts appropriately into the resources conserving mass for each fuel type, e.g.
  - 1 ore (10 kg/u) -> 2 LF (5 kg/u)
  - 1 ore (10 kg/u) -> 141 LH2 (0.07085 kg/u)

**Comment by yalov** [comment]
The mass is conserved

**Comment by yalov** [comment]
Is it ok?

**Pull request merged**
